### ISSUE TITLE
Sometimes pan buttons cause the camera to pan all the way to the side

### ISSUE THREAD

**Issue by jbermudes** [socallinuxexpo/web-control-interface#29]
This is most likely caused by the stop request getting to the camera before the move request has completed, causing an infinite pan until the hardware limit

Solution:

On camera move AJAX request success, set a flag that enables stop messages to be sent. Then, in the stop function, check the flag, and if not allowed, setTimeout for a short delay and try again.

**Comment by LeStarch** [comment]
Fixed.  Problem caused by sending requests too quickly and thus they are dropped.  Must have at lease 200ms between requests for PTZ Optics cameras.
